POST http://localhost:3001/api/setlists
Content-Type: application/json
"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1aWN5Ym9pIiwiaWQiOiI2NmIzZDlkOWNkZWZiMjhkMjlkN2QwOTAiLCJpYXQiOjE3MjMwNzYwNjEsImV4cCI6MTcyMzA3OTY2MX0.lI2MGY22cQZ-a6Hw_HIL8uN2Lz8P_iWfjWRqVzVmutc"

{
    "name": "BBQ"
}